# Generated by Django 5.1.4 on 2025-01-06 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='batch_number',
            field=models.CharField(default='DUS705', max_length=50),
        ),
    ]
